language: go
sudo: false
go:
  - 1.8.x
  - tip
before_install:
script:
  - go test 
  - go test -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - Kunde21@users.noreply.github.com
    on_success: change
    on_failure: always
